### ISSUE TITLE
BreadCrumbs Are Lost After Confirming Opening the AppStore.

### ISSUE THREAD

**Issue by ReddestDream** [hbang/StoreAlert#3]
A minor issue, but one that is kinda annoying given the convenience of BreadCrumbs on iOS 9 . . . :/

I tested this with the TouchArcade app:

https://itunes.apple.com/us/app/toucharcade-best-new-games/id509945427?mt=8

Thanks! ^_^

**Comment by kirb** [comment]
Will release later tonight, thanks :+1:

**Comment by ReddestDream** [comment]
Thank you! Just got the update! Looks like it's working! ^_^
